/* eslint-disable react-hooks/exhaustive-deps, react-refresh/only-export-components */
import {createContext,useContext,useEffect,useMemo,useRef,useState} from 'react'
import {apiRequest} from '../config/api'
import {useAuth} from './AuthContext'
const C=createContext(null),KEY='arajut-cart'
const local=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
const mapCart=d=>(d?.items||[]).map(i=>{const p=i.product;const image=p.images?.find(x=>x.is_primary)||p.images?.[0];return{id:p.id,name:p.name,slug:p.slug,price:Number(p.price),stock:p.stock,image:image?.url||image?.path,quantity:i.quantity}})
export function CartProvider({children}){const{user}=useAuth();const isCustomer=user?.role==='customer';const[items,setItems]=useState(local);const syncing=useRef(false);const load=async()=>{if(!isCustomer)return setItems(user?[]:local());try{const r=await apiRequest('/cart');setItems(mapCart(r.data))}catch{/* retain last cart */}};useEffect(()=>{const sync=async()=>{if(!isCustomer)return load();if(syncing.current)return;syncing.current=true;const guest=local();try{const current=mapCart((await apiRequest('/cart')).data);for(const item of guest){const existing=current.find(x=>x.id===item.id)?.quantity||0;await apiRequest('/cart/items',{method:'PUT',body:JSON.stringify({product_id:item.id,quantity:Math.min(existing+item.quantity,item.stock)})})}if(guest.length)localStorage.removeItem(KEY);await load()}finally{syncing.current=false}};sync()},[user]);useEffect(()=>{if(!user)localStorage.setItem(KEY,JSON.stringify(items))},[items,user]);const addItem=async(p,q=1)=>{if(isCustomer){const existing=items.find(i=>i.id===p.id)?.quantity||0;await apiRequest('/cart/items',{method:'PUT',body:JSON.stringify({product_id:p.id,quantity:Math.min(existing+q,p.stock)})});await load()}else if(!user)setItems(old=>{const x=old.find(i=>i.id===p.id);return x?old.map(i=>i.id===p.id?{...i,quantity:Math.min(i.quantity+q,p.stock)}:i):[...old,{...p,quantity:q}]})};const updateQuantity=async(id,q)=>{if(isCustomer){await apiRequest('/cart/items',{method:'PUT',body:JSON.stringify({product_id:id,quantity:q})});await load()}else if(!user)setItems(old=>old.map(i=>i.id===id?{...i,quantity:Math.max(1,Math.min(q,i.stock))}:i))};const removeItem=async id=>{if(!isCustomer){if(!user)setItems(old=>old.filter(i=>i.id!==id));return}const previous=items;setItems(old=>old.filter(i=>i.id!==id));try{const response=await apiRequest(`/cart/items/${id}`,{method:'DELETE'});setItems(mapCart(response.data))}catch(error){setItems(previous);throw error}};const value=useMemo(()=>({items,addItem,updateQuantity,removeItem,refreshCart:load,count:items.reduce((n,i)=>n+i.quantity,0),total:items.reduce((n,i)=>n+i.price*i.quantity,0)}),[items]);return <C.Provider value={value}>{children}</C.Provider>}
export const useCart=()=>useContext(C)
